# CUADERNO DE APRENDIZAJE DE PANDA
----------------------------------------------------------------------------------------------------------------------------------------------

# Ejercicio Ecommerce

En este ejercicio, se proporcionan datos ficticios sobre compras realizadas por Amazon, por lo que es posible que exista alguna incoherencia en los datos. Se trata de ir realizando cada uno de los ejercicios propuestos progresivamente. Hay más de una forma de hacerlos, y todos se pueden responder con una línea.

El enlace es:

```python
URL_data = 'https://raw.githubusercontent.com/MatinMasimli/DataScience_ML_Udemy_Exercises/master/Ecommerce_purchases/Ecommerce%20Purchases.csv'
```

Cargamos la librería pandas como 'pd' y numpy como 'np':

In [1]:
import pandas as pd
import numpy as np

Ahora, leemos el DataFrame y mostramos sus cinco primeras filas:

In [2]:
df = pd.read_csv('/Users/lia/Desktop/Upgrade_Hub/Temario/Modulo 1/1.4. Pandas/Ejercicio_ecommerce/ejercicio_ecommerce/data/Ecommerce Purchases.csv')

¿Qué dimensiones tienen nuestros datos?

In [3]:
df.head(5) #me da las primeras filas, asi puedo ver facilmente los nombres de las columnas para trabajar con ellas

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

In [4]:
df.shape #me da los valores totales en numero de filas y numero de columnas

(10000, 14)

In [5]:
df.isnull().sum() #comprobar nulos

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

In [6]:
df.duplicated() #comprobar duplicados

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [7]:
df.duplicated().sum() #poniendo el .sum() me da el sumatorio de los duplicados que haya

np.int64(0)

In [8]:
df.columns #me da el nombre de las columnas

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='object')

In [9]:
df.info() #info del df a nivel general, tipos de datos, recuentos totales, etc

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB

*Respuesta esperada:*

```python
(10000,14)
```

¿Cuál es el precio medio de compra?

In [10]:
df['Purchase Price'].mean()

np.float64(50.347302)

In [11]:
df['Purchase Price'].mean().round(2) #poniendo al final el .round(2) hago que el numero me de solo dos decimales

np.float64(50.35)

*Respuesta esperada:*

```python
50.34730200000025
```

Cuáles fueron, respectivamente, los precios mayores y menores de compra?

In [12]:
max_price = df['Purchase Price'].max()
print(f'El precio mayor es {max_price}')

El precio mayor es 99.99

*Respuesta esperada:*

```python
99.989999999999995
```

In [13]:
min_price = df['Purchase Price'].min()
print(f'El precio menor es {min_price}')

El precio menor es 0.0

*Respuesta esperada:*

```python
0.0
```

¿Cuánta gente tiene indicado como inglés (valor 'en') el idioma preferente?

In [14]:
df['Language'].unique() #aqui saco los valores unicos de la columna language, porque no recordaba como estaba escrito

array(['el', 'fr', 'de', 'es', 'ru', 'pt', 'zh', 'en', 'it'], dtype=object)

In [15]:
df['Language'].value_counts()

Language
de    1155
ru    1155
el    1137
pt    1118
en    1098
fr    1097
es    1095
it    1086
zh    1059
Name: count, dtype: int64

In [16]:
english_speakers = df['Language'].value_counts()['en']
print(english_speakers)

1098

*Respuesta esperada:*

```python
1098
```

¿Cuánta gente dispone del título profesional `'Lawyer'`?

In [17]:
lawyers = df['Job'].value_counts()['Lawyer']
print(lawyers)

30

*Respuesta esperada:*

```python
30
```

¿Cuántas personas hicieron compras durante la mañana, y cuántas durante la tarde?

*(Pista: Use [value_counts()](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html))*

In [18]:
df['AM or PM'].value_counts() #al haber solo dos valores, no es necesario llamar a cada uno por separado, con el general veo los dos

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

In [19]:
am_purchases = df['AM or PM'].value_counts()['AM']
print(f'Por la mañana se hicieron {am_purchases} compras.')

pm_purchases = df['AM or PM'].value_counts()['PM']
print(f'Por la tarde se hicieron {pm_purchases} compras.')

Por la mañana se hicieron 4932 compras.
Por la tarde se hicieron 5068 compras.

*Respuesta esperada:*

```python
PM    5068
AM    4932
Name: AM or PM, dtype: int64
```

¿Cuáles son las cinco profesiones más habituales?

In [20]:
common_jobs = df['Job'].mode()

*Respuesta esperada:*

```python
Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Purchasing manager               27
Designer, jewellery              27
Name: Job, dtype: int64
```

In [21]:
df['Job'].value_counts().head(5) #hacer un value_counts primero y decir que me de los n primeros ya me da los mas comunes

Job
Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Purchasing manager               27
Designer, jewellery              27
Name: count, dtype: int64

In [22]:
df['Job'].value_counts().tail(5) #igual pero para sacar las ultimas posiciones

Job
Prison officer                 7
Editor, film/video             6
Actuary                        6
Information systems manager    5
Investment analyst             5
Name: count, dtype: int64

Algún usuario hizo una compra que vino en el lote `90 WT`. ¿Cuál fue el precio de esa transacción?

In [23]:
precio_90wt = df[df['Lot'] == '90 WT']['Purchase Price']
print(precio_90wt)

513    75.1
Name: Purchase Price, dtype: float64

In [24]:
df['Purchase Price'][df['Lot'] == '90 WT'] #se puede seleccionar lo que quiero tando al inicio como al final

513    75.1
Name: Purchase Price, dtype: float64

*Respuesta esperada:*

```python
513    75.1
Name: Purchase Price, dtype: float64
```

¿Cuál es el email de la persona con tarjeta de crédito `4926535242672853`?

In [25]:
email = df[df['Credit Card'] == 4926535242672853]['Email']
email

1234    bondellen@williams-garza.com
Name: Email, dtype: object

*Respuesta esperada:*

```python
1234    bondellen@williams-garza.com
Name: Email, dtype: object
```

¿Cuánta gente tiene `American Express` como proveedor de crédito e hizo una compra superior a `$95`?

In [26]:
amex_plus_95_usd = df[(df['CC Provider'] == 'American Express') & (df['Purchase Price'] > 95)].shape[0]
amex_plus_95_usd
#el shape me vale para saber cuantas filas, columnas me da. 
# le pongo un 0 para saber el numero total de filas que tiene el filtro
#si le pongo 1 me daria las columnas

39

In [27]:
df[(df['CC Provider'] == 'American Express') & (df['Purchase Price'] > 95)].shape[0] 

#si no pongo el .shape[0] al final me daria todo el dataset que reune esas dos condiciones, con el shape me las cuenta

39

*Respuesta esperada:*

```python
39
```

¿Cuánta gente tiene una tarjeta de crédito que expira en 2025?

In [28]:
def expiration_year(x):
    return x.split('/')[1]
count_2025 = df['CC Exp Date'].apply(expiration_year).value_counts().get('25', 0)
print(f"Cantidad de personas con tarjeta de crédito que expira en 2025: {count_2025}")

Cantidad de personas con tarjeta de crédito que expira en 2025: 1033

In [29]:
expiration_2025 = df[df['CC Exp Date'].str.endswith('25')].shape[0] 
    # str.endswith('25') para filtrar las filas donde la fecha de expiración de la tarjeta de crédito termina en '25'.
    # .shape[0] para contar cuántas filas cumplen con esta condición.

*Respuesta esperada:*

```python
1033
```

¿Cuáles fueron los cinco *email hosts* más populares (e.g., gmail, yahoo,...)?

In [30]:
df['Email'].apply(lambda x: x.split('@')[1]).head(5)

0               yahoo.com
1                reed.com
2    morales-harrison.com
3     olson-robinson.info
4               gmail.com
Name: Email, dtype: object

In [31]:
# 1. Extraer el host del email (lo que está después de '@') 
df['email_host'] = df['Email'].str.split('@').str[1]

# 2. Contar las ocurrencias de cada host
email_host_counts = df['email_host'].value_counts()

# 3. Obtener los cinco hosts más comunes
top_5_hosts = email_host_counts.head(5)

print(top_5_hosts)

email_host
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64

*Respuesta esperada:*

```python
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: Email, dtype: int64
```